n=input('Digite algo ')
print('Qual e tipo primitivo? ',type(n))
print('So tem espaços? ',n.isspace())
print('E um alfanumerico? ',n.isalnum())
print('E um numerico? ',n.isnumeric())
print('E alfabetico? ',n.isalpha())
print('Esta em minusculo? ',n.islower())
print('Esta em maiuscula? ',n.isupper())
print('Esta capitalizada ',n.istitle())